# Ask: request 'Read'
# id        : The discribtion you want to name. 
# item      : More details please refer to the TM_Robot_Expression.pdf(1.76 rev1.00) Chapter 7.4 TMSCT
# wait_time : set wait time.
# More details please refer to the TM_Robot_Expression.pdf(version 1.76_6300) Chapter 7.4 TMSCT

string id
string item

float64 wait_time

---
# ok        : read status 
bool ok

# id        : The discribtion you want to name.
# value     : The value of asked item.
string id
string value
