# Ask: request 'Read' sta
# More details please refer to the TM_Robot_Expression.pdf(1.76 rev1.00) Chapter 7.5 TMSTA
# wait_time : set wait time.

string subcmd
string subdata

float64 wait_time

---
# ok        : read status 
bool ok

string subcmd
string subdata