# More details please refer to the tm_eos_service.cpp/set_event function.
int8 TAG = 1
int8 WAIT_TAG = 2
int8 STOP = 11
int8 PAUSE = 12
int8 RESUME = 13

int8 EXIT = -1

int8 func

int8 arg0
int8 arg1

---
#ok == complete status
bool ok
# int8 rv
